### ISSUE TITLE
Furion documentation - dbcontext

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#61]

**Comment by HonghuiHu** [comment]
当使用IActionFilter时，在过滤器里面获取服务，调用访问了数据库的方法，便经常报错，每次报错位置不一，但是都是某访问数据库的相关操作报错：A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
已确认：所有访问数据库的异步操作全部await了
如过滤器加了以下两句：
var _systemService=App.GetService<ISystemService>();
 var permissions = await _systemService.GetMenuByUserIdAsync(user.Id);

GetMenuByUserIdAsync方法如下
public async Task<List<string>> GetMenuByUserIdAsync(string userId)
        {
            var query = from a in _userRepository.DetachedEntities
                        join b in _userRoleRepository.DetachedEntities on a.Id equals b.UserId
                        join c in _roleMenuRepository.DetachedEntities on b.RoleId equals c.RoleId
                        join d in _menuRepository.DetachedEntities on c.MenuId equals d.Id
                        where a.Id == userId
                        select d.Path;
            return await query.ToListAsync();
        }

**Comment by HonghuiHu** [comment]
当在过滤器里 用 Scoped.Create((_, scope) => 这种方式里面创建Service  便正常 
Scoped.Create((_, scope) =>
                {
                    var services = scope.ServiceProvider;


                    ISystemService _systemService = App.GetService<ISystemService>(services);   // services 传递进去
                    //var _systemService = App.GetService<ISystemService>();
                    var permissions =  _systemService.GetMenuByUserIdAsync(user.Id).Result;

**Comment by HonghuiHu** [comment]
目前看来时因为过滤器的OnActionExecuting  我标记了异步导致的
